services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres-db-container
    volumes:
      - postgres:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD

  patient-service:
    depends_on:
      - postgres
    image: patient-service:0.0.1
    container_name: patient-service-container
    ports:
      - "8090:8090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  gateway-service:
    image: gateway-service:0.0.1
    container_name: gateway-service-container
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      SPRING_APPLICATION_NAME: gateway-service
    depends_on:
      - patient-service

volumes:
  postgres: