services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    container_name: postgres-db-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 10

  mongodb:
    image: mongo:latest
    container_name: mongo-db-container
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')",
              "-u", "${MONGODB_USERNAME}", "-p", "${MONGODB_PASSWORD}",
              "--authenticationDatabase","admin" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  note-service:
    build: ./note-service
    image: note-service:0.0.1
    container_name: note-service-container
    restart: unless-stopped
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      MONGODB_URI: ${MONGODB_URI}
    ports:
      - "8083:8083"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  patient-service:
    build: ./patient-service
    image: patient-service:0.0.1
    container_name: patient-service-container
    ports:
      - "8090:8090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8090/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

  risk-assessment-service:
    build: ./risk-assessment-service
    image: risk-assessment-service:0.0.1
    container_name: risk-assessment-service-container
    restart: unless-stopped
    ports:
      - "8084:8084"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8084/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

  authentication-service:
    build: ./authentication-service
    image: authentication-service:0.0.1
    container_name: authentication-service-container
    restart: unless-stopped
    ports:
      - "8085:8085"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_AUTH_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SERVER_PORT: 8085
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8085/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

  gateway-service:
    build: ./gateway-service
    image: gateway-service:0.0.1
    container_name: gateway-service-container
    restart: unless-stopped
    ports:
      - "18080:8081"
    environment:
      PATIENT_SERVICE_URI: http://patient-service:8090
      NOTE_SERVICE_URI: http://note-service:8083
      RISK_ASSESSMENT_SERVICE_URI: http://risk-assessment-service:8084
    depends_on:
      patient-service:
        condition: service_healthy
      authentication-service:
        condition: service_healthy
      note-service:
        condition: service_healthy
      risk-assessment-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend-service:
    build: ./frontend-service
    image: frontend-service:0.0.1
    container_name: frontend-service-container
    restart: unless-stopped
    ports:
      - "18081:8082"
    environment:
      GATEWAY_URL: http://gateway-service:8081
    depends_on:
      gateway-service:
        condition: service_healthy
volumes:
  postgres:
  mongo-data: