server.port=8082
spring.application.name=frontend-service

gateway-url=http://localhost:8081

gateway-service-uri=${gateway-url}
patient-service-uri=${gateway-service-uri}/patient-service

# Active the filter for convert from POST Request to PUT, DELETE Method
spring.mvc.hiddenmethod.filter.enabled=true