server.port=8081
spring.application.name=gateway-service

logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.reactor.netty=DEBUG

# patient-service API
patient-service-uri=${PATIENT_APPLICATION_URI:http://localhost:8090}
# note-service API
note-service-uri=${NOTE_APPLICATION_URI:http://localhost:8083}
## risk-service API
#risk-service-uri=${RISK_APPLICATION_URI:localhost:8084}
# authentication-service API
authentication-service-uri=http://authentication-service-container:8085/
# authentication-service API Token Validation URI
authentication-service-token-validation-uri=${authentication-service-uri}authentication/validate?token=%s

management.endpoint.web.exposure.include=health