server.port=8081
spring.application.name=gateway-service

# patient-service API
patient-service-uri=http://localhost:8090
# frontend-service API
frontend-service-uri=:http://localhost:8082
# note-service API
note-service-uri=http://localhost:8083
# risk-service API
risk-assessment-service-uri=http://localhost:8084
# authentication-service API
authentication-service-uri=http://localhost:8085/
# authentication-service API Token Validation URI
authentication-service-token-validation-uri=${authentication-service-uri}authentication/validate?token=%s
