server:
  port: 8081

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: patient-service-route
              uri: http://patient-service-container:8090
              predicates:
                - Path=/patient-service/**

            - id: authentication-service-route
              uri: http://authentication-service-container:8085
              predicates:
                  - Path=/authentication/**
management:
  endpoint:
    web:
      exposure:
        include: health