server.port=8084
spring.application.name=risk-assessment-service

gateway-service-uri=http://localhost:8081
patient-service-uri=${gateway-service-uri}/patients
note-service-uri=${gateway-service-uri}/notes