server.port=8084
spring.application.name=risk-assessment-service

gateway-service-uri=http://gateway-service-container:8081
patient-service-uri=${gateway-service-uri}/patients
note-service-uri=${gateway-service-uri}/notes

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always