spring.application.name=authentication-application
server.port=8085

spring.datasource.url=jdbc:h2:mem:msauth
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

jwt.secret-key=Cko2y7KSh8N1j8DO8wEuwOlBMnQ2RHias57AnSgo3to=