server.port=8083
spring.application.name=note-service

spring.data.mongodb.uri=mongodb://root:password@mongo-db-container:27017/notes_db?authSource=admin

management.endpoints.web.exposure.include=health